#!/usr/bin/env python3
import subprocess
import os
from pathlib import Path


def execute_shell_command(cmd, work_dir, env_vars={}):
    pipe = subprocess.Popen(cmd, shell=True, env={**os.environ, **env_vars}, cwd=work_dir,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, error = pipe.communicate()
    print(out.decode(), error.decode())
    return out, error


def git_get_new_files(repo_path):
    cmd = 'git diff --cached --name-only --diff-filter A'
    files, _ = execute_shell_command(cmd, repo_path)
    files = files.decode()
    return files.split('\n')[:-1]


def main():
    path = Path('test-repo/').resolve()
    files = git_get_new_files(path)
    print(files)


if __name__ == "__main__":
    main()
