#!/home/babu/code/git-hook-repl.it/.venv/bin/python
import subprocess
import os
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import pyperclip


def execute_shell_command(cmd, work_dir, env_vars={}):
    pipe = subprocess.Popen(cmd, shell=True, env={**os.environ, **env_vars}, cwd=work_dir,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, error = pipe.communicate()
    return out, error


def git_get_new_files(repo_path):
    cmd = 'git diff --cached --name-only --diff-filter A'
    files, _ = execute_shell_command(cmd, repo_path)
    files = files.decode()
    return files.split('\n')[:-1]


def git_get_modified_files(repo_path):
    cmd = 'git diff --cached --name-only --diff-filter M'
    files, _ = execute_shell_command(cmd, repo_path)
    files = files.decode()
    return files.split('\n')[:-1]


def get_file_contents(file):
    with open(file) as f:
        contents = f.read()
        return contents


def repl_login(driver, username, password):
    driver.get('https://repl.it/login')
    username_element = driver.find_element_by_xpath(
        '//form//input[@name="username"]')
    username_element.clear()
    username_element.send_keys(username)
    password_element = driver.find_element_by_xpath(
        '//form//input[@name="password"]')
    password_element.clear()
    password_element.send_keys(password)
    password_element.send_keys(Keys.ENTER)

    search_bar_path = '//input[@placeholder="Search"]'
    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.XPATH, search_bar_path))
    )


def repl_create(driver, repl_name):
    driver.get('https://repl.it/languages/cpp11')

    edit_name_button = driver.find_element_by_xpath(
        '//*[name()="svg" and @class="pencil-icon-svg"]')
    edit_name_button.click()

    name_element_path = '//div[contains(concat(" ", normalize-space(@class), " "), " edit-repl ")]//input'
    name_element = driver.find_element_by_xpath(name_element_path)
    name_element.clear()
    name_element.send_keys(repl_name)
    name_element.send_keys(Keys.ENTER)
    WebDriverWait(driver, 10).until(
        EC.title_contains(repl_name)
    )

    return driver.current_url


def repl_change_contents(driver, repl_url, repl_contents):
    driver.get(repl_url)

    code_editor_path = '//div[contains(concat(" ", normalize-space(@class), " "), " replit-monaco-editor-container ")]'
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, code_editor_path))
    )
    code_editor_element = driver.find_element_by_xpath(code_editor_path)
    code_editor_element.click()

    pyperclip.copy(repl_contents)

    clear_repl = ActionChains(driver)
    clear_repl.key_down(Keys.CONTROL).send_keys(
        'a').key_up(Keys.CONTROL).send_keys(Keys.DELETE)
    clear_repl.perform()

    paste_repl_contents = ActionChains(driver)
    paste_repl_contents.key_down(
        Keys.CONTROL).send_keys('v').key_up(Keys.CONTROL)
    paste_repl_contents.perform()

    save_status_path = '//span[text()="saved"]'
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, save_status_path))
    )


def repl_add(driver, files_added):
    for file in files_added:
        url = repl_create(driver, file.stem)
        contents = get_file_contents(file)
        repl_change_contents(driver, url, contents)


def repl_modify(driver, username, files_modified):
    url_start = f'https://repl.it/@{username}/'
    for file in files_modified:
        url = url_start + file.stem
        contents = get_file_contents(file)
        repl_change_contents(driver, url, contents)


def main():
    path = Path('test-repo/').resolve()
    files_added = git_get_new_files(path)
    files_modified = git_get_modified_files(path)

    files_added = [path / file for file in files_added]
    files_modified = [path / file for file in files_modified]
    print(files_added)
    print(files_modified)

    username, password = "", ""
    with open("creds") as f:
        username = f.readline()[:-1]
        password = f.readline()

    driver = webdriver.Chrome()

    repl_login(driver, username, password)
    repl_add(driver, files_added)
    repl_modify(driver, username, files_modified)

    input()


if __name__ == "__main__":
    main()
