#!/home/babu/code/git-hook-repl.it/.venv/bin/python
import subprocess
import os
from pathlib import Path
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


def execute_shell_command(cmd, work_dir, env_vars={}):
    pipe = subprocess.Popen(cmd, shell=True, env={**os.environ, **env_vars}, cwd=work_dir,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, error = pipe.communicate()
    return out, error


def git_get_new_files(repo_path):
    cmd = 'git diff --cached --name-only --diff-filter A'
    files, _ = execute_shell_command(cmd, repo_path)
    files = files.decode()
    return files.split('\n')[:-1]


def git_get_modified_files(repo_path):
    cmd = 'git diff --cached --name-only --diff-filter M'
    files, _ = execute_shell_command(cmd, repo_path)
    files = files.decode()
    return files.split('\n')[:-1]


def get_file_contents(file):
    with open(file) as f:
        contents = f.read()
        return contents


def repl_login(driver, username, password):
    driver.get('https://repl.it/login')
    username_element = driver.find_element_by_xpath(
        '//form//input[@name="username"]')
    username_element.clear()
    username_element.send_keys(username)
    password_element = driver.find_element_by_xpath(
        '//form//input[@name="password"]')
    password_element.clear()
    password_element.send_keys(password)
    password_element.send_keys(Keys.ENTER)


def repl_create(driver, repl_name):
    search_bar_path = '//input[@placeholder="Search"]'
    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.XPATH, search_bar_path))
    )
    driver.get('https://repl.it/languages/cpp11')

    edit_name_button = driver.find_element_by_xpath(
        '//*[name()="svg" and @class="pencil-icon-svg"]')
    edit_name_button.click()

    name_element_path = '//div[contains(concat(" ", normalize-space(@class), " "), " edit-repl ")]//input'
    name_element = driver.find_element_by_xpath(name_element_path)
    name_element.clear()
    name_element.send_keys(repl_name)
    name_element.send_keys(Keys.ENTER)
    WebDriverWait(driver, 10).until(
        EC.title_contains(repl_name)
    )


def main():
    path = Path('test-repo/').resolve()
    files_added = git_get_new_files(path)
    files_modified = git_get_modified_files(path)
    print(files_added)
    print(files_modified)
    driver = webdriver.Chrome()
    username, password = "", ""
    with open("creds") as f:
        username = f.readline()[:-1]
        password = f.readline()
    repl_login(driver, username, password)
    repl_create(driver, files_modified[0][:-4])
    input()


if __name__ == "__main__":
    main()
